apiVersion: batch/v1
kind: Job
metadata:
  labels:
    controlledBy: DbOperator
  name: example-backup-job
  namespace: default
spec:
  backoffLimit: 6
  completions: 1
  parallelism: 1
  selector:
    matchLabels:
      controller-uid: f8036931-9717-46e4-a100-12b462698fd4
  template:
    metadata:
      creationTimestamp: null
      labels:
        controller-uid: f8036931-9717-46e4-a100-12b462698fd4
        job-name: example-backup-job
    spec:
      containers:
      - command:
        - /scripts/backup_postgres.sh
        env:
        - name: PGHOST
          value: localhost
        - name: PGUSER
          value: postgres
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: postgres
        - name: DATABASE
          value: some-example-database
        image: postgres:latest
        imagePullPolicy: Always
        name: pg-dump
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /scripts
          name: scripts
        - mountPath: /pgdump
          name: pgdump
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 511
          name: db-operator-scripts
        name: scripts
      - name: pgdump
