# permissions for end users to view backupcronjobs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: backupcronjob-viewer-role
rules:
- apiGroups:
  - db-operator.kubemaster.com
  resources:
  - backupcronjobs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - db-operator.kubemaster.com
  resources:
  - backupcronjobs/status
  verbs:
  - get
