# permissions for end users to view backuptargets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: backuptarget-viewer-role
rules:
- apiGroups:
  - db-operator.kubemaster.com
  resources:
  - backuptargets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - db-operator.kubemaster.com
  resources:
  - backuptargets/status
  verbs:
  - get
