# permissions for end users to edit dbs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: db-editor-role
rules:
- apiGroups:
  - db-operator.kubemaster.com
  resources:
  - dbs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - db-operator.kubemaster.com
  resources:
  - dbs/status
  verbs:
  - get
