# permissions for end users to view dbcopycronjobs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dbcopycronjob-viewer-role
rules:
- apiGroups:
  - db-operator.kubemaster.com
  resources:
  - dbcopycronjobs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - db-operator.kubemaster.com
  resources:
  - dbcopycronjobs/status
  verbs:
  - get
