# permissions for end users to view dbservers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dbserver-viewer-role
rules:
- apiGroups:
  - db-operator.kubemaster.com
  resources:
  - dbservers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - db-operator.kubemaster.com
  resources:
  - dbservers/status
  verbs:
  - get
