# permissions for end users to view restorecronjobs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: restorecronjob-viewer-role
rules:
- apiGroups:
  - db-operator.kubemaster.com
  resources:
  - restorecronjobs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - db-operator.kubemaster.com
  resources:
  - restorecronjobs/status
  verbs:
  - get
