# permissions for end users to view restoretargets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: restoretarget-viewer-role
rules:
- apiGroups:
  - db-operator.kubemaster.com
  resources:
  - restoretargets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - db-operator.kubemaster.com
  resources:
  - restoretargets/status
  verbs:
  - get
