# permissions for end users to view restorejobs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: restorejob-viewer-role
rules:
- apiGroups:
  - db-operator.kubemaster.com
  resources:
  - restorejobs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - db-operator.kubemaster.com
  resources:
  - restorejobs/status
  verbs:
  - get
