# permissions for end users to view s3storages.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: s3storage-viewer-role
rules:
- apiGroups:
  - db-operator.kubemaster.com
  resources:
  - s3storages
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - db-operator.kubemaster.com
  resources:
  - s3storages/status
  verbs:
  - get
