## Append samples you want in your CSV to this file as resources ##
resources:
- db-operator_v1alpha1_dbserver.yaml
- db-operator_v1alpha1_db.yaml
- db-operator_v1alpha1_user.yaml
#+kubebuilder:scaffold:manifestskustomizesamples
