{{- range .Values.Dbs }}
apiVersion: db-operator.kubemaster.com/v1alpha1
kind: Db
metadata:
  name: {{ quote .name }}
spec:
  db_name: {{ quote .db_name }}
  drop_on_deletion: {{ .drop_on_deletion }}
  server: {{ quote .server }}
---
{{ end -}}