{{- range .Values.RestoreTargets }}
apiVersion: db-operator.kubemaster.com/v1alpha1
kind: RestoreTarget
metadata:
  name: {{ quote .name }}
spec:
  db_name: {{ quote .db_name }}
  storage_type: {{ quote .storage_type }}
  storage_location: {{ quote .storage_location }}
---
{{ end -}}